/*  Part of XPCE --- The SWI-Prolog GUI toolkit

    Author:        Anja van der Hulst
    WWW:           https://www.swi-prolog.org/packages/xpce/
    Copyright (c)  1995-2026, University of Amsterdam
                              SWI-Prolog Solutions b.v.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in
       the documentation and/or other materials provided with the
       distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
This demo illustrates (like the juggler  demo) annimation in  xpce.  A
timer is attached to the drawing area that moves all graphicals in the
window by step/1 points and sets them in the next annimation status.

A kangaroo is a figure holding the frames of a hop as bitmaps.  The
images are SVG documents that are generated by this file and loaded from
a text_buffer.  The kangaroo is drawn from a _pose_: the body pitch and
the directions of thigh, shin, foot, tail and arm.  A hop of frames/1
frames interpolates between the key poses of key_pose/8.  Each frame
shifts the kangaroo inside the image such that, combined with the
constant step, its feet stay on the ground while it crouches and all
forward motion happens in the air.  Each body part is drawn twice:
first with a thick stroke in the outline colour and then filled without
stroke.  This gives a single outline around the silhouette of the whole
body.  The kangaroos come in the colours of palette/6.

Left-click in the drawing area adds a kangaroo to the diagram.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

:- module(kangaroo, [ kangaroo/0]).
:- use_module(library(pce)).
:- use_module(library(apply)).
:- use_module(library(lists)).
:- use_module(library(pairs), [pairs_keys_values/3]).

kangaroo :-
    step(Step),
    new(Pict, window('Kangaroo animation demo', size(640, 240))),
    new(Msg, message(Pict?graphicals, for_all,
                     and(message(@arg1, next_status),
                         if(@arg1?right_side > Pict?visible?right_side,
                            message(@arg1, x, 0),
                            message(@arg1, relative_move, point(Step, 0)))))),
    send(Pict, attribute, attribute(timer, new(T, timer(0.1, Msg)))),
    send(T, start),

    send(Pict, recogniser,
         click_gesture(left, '', single,
                       message(@prolog, new_kangaroo,
                               @receiver, @event?position))),

    send(new(D, dialog), below, Pict),
    send(D, append,
         label(help, 'Left-click in the main window for a new kangaroo')),
    send(D, append,
         slider(speed, 0, 10, 2, message(@prolog, set_speed, T, @arg1))),

    send(D, append, button(clear, message(Pict, clear))),
    send(D, append, new(Quit, button(quit, and(message(T, free),
                                               message(D, destroy))))),
    send(D, done_message, message(Quit, execute)),

    new_kangaroo(Pict, point(20,100)),

    send(Pict, open).


set_speed(T, 0) :-
    !,
    send(T, stop).
set_speed(T, N) :-
    Time is 1/(9*N),
    send(T, interval, Time),
    send(T, running, @on).

%!  new_kangaroo(+Pict, +Pos)
%
%   Add a kangaroo at Pos.  Each new kangaroo has the next colour and
%   starts at a random moment of its hop.

new_kangaroo(Pict, Pos) :-
    findall(C, palette(C, _, _, _, _, _), Colours),
    length(Colours, NC),
    flag(kangaroo_colour, I, I+1),
    Nth is I mod NC,
    nth0(Nth, Colours, Colour),
    frames(Frames),
    new(F, figure),
    forall(between(1, Frames, N),
           ( kangaroo_image(Colour, N, Image),
             send(F, display, new(BM, bitmap(Image))),
             send(BM, name, N)
           )),
    random_between(1, Frames, Start),
    send(F, status, Start),
    send(Pict, display, F, Pos).

%!  kangaroo_image(+Colour, +N, -Image) is det.
%
%   Image is frame N (1-based) of a kangaroo in Colour.  The images are
%   generated on first use and shared by all kangaroos of this colour.

:- dynamic
    image_cache/3,                      % Colour, N, Image
    base_x_/1.

kangaroo_image(Colour, N, Image) :-
    image_cache(Colour, N, Image),
    !.
kangaroo_image(Colour, N, Image) :-
    base_x(BaseX),
    I is N-1,
    frame(I, Colour, BaseX, _, SVG),
    new(TB, text_buffer),
    send(TB, insert, 0, SVG),
    pixels(Width),
    new(Image, image(TB, Width)),
    send(Image, lock_object, @on),
    assertz(image_cache(Colour, N, Image)).

base_x(BaseX) :-
    base_x_(BaseX0),
    !,
    BaseX = BaseX0.
base_x(BaseX) :-
    layout(BaseX),
    assertz(base_x_(BaseX)).

		 /*******************************
		 *          PARAMETERS		*
		 *******************************/

frames(12).                     % frames per hop
canvas(240, 160).               % viewBox of a frame
pixels(150).                    % width in pixels the demo shows a frame at
step(8).                        % pixels the demo moves a figure per tick
ground_y(150).                    % y of the ground in the viewBox
jump(34).                       % height of the hop
contact(0.34).                  % fraction of the hop on the ground
figure_scale(0.72).             % scale of the figure
stroke_width(3.2).              % width of the outline

%!  palette(?Name, -Body, -Shade, -Belly, -Outline, -Ear)
%
%   Colours of a kangaroo.  Shade is the colour of the far limbs.

palette(red,    '#c8643b', '#a24a29', '#f6d2b0', '#4a2414', '#e9a07f').
palette(grey,   '#8e949e', '#6f757f', '#e4e7eb', '#2c3038', '#c9a3a8').
palette(golden, '#e0a542', '#bc8325', '#fbe8bf', '#5a3a0c', '#f2c27a').
palette(blue,   '#4f8fd6', '#3970b4', '#d5e7fb', '#16314f', '#9cc4ef').

%!  key_pose(?T, ?HipHeight, ?Pitch, ?Thigh, ?Shin, ?Foot, ?Tail, ?Arm)
%
%   Key poses of the hop.  T is the moment in the hop (0..1).  Angles
%   are in degrees.  Pitch is the angle of the body axis above
%   horizontal.  Thigh, Shin and Foot are the direction of the segment:
%   0 points forward (right), 90 down and 180 backward.  Tail is the
%   direction of the tail base, 180 is straight back.  HipHeight is not
%   used: the height follows from the feet.

key_pose(0.00, 38, 30,  25, 125,  12, 205, 110).  % landing: legs forward
key_pose(0.17, 30, 22,   0, 150,   4, 210, 120).  % deep crouch
key_pose(0.34, 56, 45, 115, 145, 115, 175,  95).  % take-off: legs back
key_pose(0.55, 60, 42, 125, 145, 150, 178,  80).  % flight: legs trailing
key_pose(0.78, 58, 36,  70, 110,  40, 185,  95).  % legs swing forward
key_pose(0.92, 46, 32,  35, 115,  10, 195, 105).  % reaching for the ground
key_pose(1.00, 38, 30,  25, 125,  12, 205, 110).

		 /*******************************
		 *            POSE		*
		 *******************************/

%!  pose(+T, -Pose:list) is det.
%
%   Interpolate the key poses at moment T, easing in and out of each
%   key pose.

pose(T, Pose) :-
    findall(K-P, key_pose_list(K, P), Keys),
    append(_, [T0-P0, T1-P1|_], Keys),
    T0 =< T, T =< T1,
    !,
    ease((T-T0)/(T1-T0), F),
    maplist(lerp(F), P0, P1, Pose).

key_pose_list(T, [HH,P,Th,Sh,Ft,Tl,Ar]) :-
    key_pose(T, HH, P, Th, Sh, Ft, Tl, Ar).

lerp(F, A, B, V) :-
    V is A + (B-A)*F.

ease(F, V) :-
    V is 0.5 - 0.5*cos(pi*F).

%!  pt(+P0, +Angle, +Length, -P) is det.
%
%   P is Length from P0 in direction Angle (degrees).

pt(X0-Y0, Ang, Len, X-Y) :-
    A is Ang*(pi/180),
    X is X0 + cos(A)*Len,
    Y is Y0 + sin(A)*Len.

		 /*******************************
		 *           SHAPES		*
		 *******************************/

%!  capsule(+Points, +Widths, -Shape) is det.
%
%   A tapered stroke through Points with the given half widths, as a
%   closed smooth shape.

capsule(Points, Widths, smooth(Poly)) :-
    length(Points, Len),
    numlist(1, Len, Is),
    maplist(side_points(Points), Is, Widths, Left, Right),
    reverse(Right, RRight),
    append(Left, RRight, Poly).

side_points(Points, I, W, LX-LY, RX-RY) :-
    nth1(I, Points, X-Y),
    length(Points, Len),
    (   I == 1
    ->  nth1(2, Points, X2-Y2), DX is X2-X, DY is Y2-Y
    ;   I == Len
    ->  Ip is I-1, nth1(Ip, Points, X0-Y0), DX is X-X0, DY is Y-Y0
    ;   Ip is I-1, In is I+1,
        nth1(Ip, Points, X0-Y0), nth1(In, Points, X2-Y2),
        DX is X2-X0, DY is Y2-Y0
    ),
    N0 is sqrt(DX*DX+DY*DY),
    ( N0 =:= 0 -> N = 1 ; N = N0 ),
    NX is -DY/N, NY is DX/N,
    LX is X+NX*W, LY is Y+NY*W,
    RX is X-NX*W, RY is Y-NY*W.

%!  catmull(+Poly, -PathData) is det.
%
%   PathData is SVG path data for a closed Catmull-Rom spline through
%   the points of Poly.

catmull(Poly, Data) :-
    length(Poly, N),
    Poly = [X0-Y0|_],
    format(string(Start), 'M~1f,~1f', [X0, Y0]),
    Last is N-1,
    numlist(0, Last, Is),
    maplist(catmull_segment(Poly, N), Is, Segments),
    append([Start|Segments], [" Z"], Parts),
    atomic_list_concat(Parts, Data).

catmull_segment(Poly, N, I, Seg) :-
    I0 is (I-1+N) mod N, I2 is (I+1) mod N, I3 is (I+2) mod N,
    nth0(I0, Poly, X0-Y0), nth0(I, Poly, X1-Y1),
    nth0(I2, Poly, X2-Y2), nth0(I3, Poly, X3-Y3),
    C1X is X1 + (X2-X0)/6, C1Y is Y1 + (Y2-Y0)/6,
    C2X is X2 - (X3-X1)/6, C2Y is Y2 - (Y3-Y1)/6,
    format(string(Seg), ' C~1f,~1f ~1f,~1f ~1f,~1f',
           [C1X, C1Y, C2X, C2Y, X2, Y2]).

%!  svg_shape(+Shape, +Fill, +Stroke, -SVG) is det.
%
%   SVG element for Shape.  Stroke is `none` or stroke(Colour, Width).

svg_shape(Shape, Fill, Stroke, SVG) :-
    shape_style(Fill, Stroke, Style),
    svg_element(Shape, Style, SVG).

shape_style(Fill, none, Style) :-
    !,
    format(string(Style), 'fill="~w"', [Fill]).
shape_style(Fill, stroke(Colour, Width), Style) :-
    format(string(Style),
           'fill="~w" stroke="~w" stroke-width="~1f" stroke-linejoin="round"',
           [Fill, Colour, Width]).

svg_element(ellipse(CX, CY, RX, RY, A), Style, SVG) :-
    format(string(SVG),
           '<ellipse cx="~1f" cy="~1f" rx="~1f" ry="~1f" \c
            transform="rotate(~1f ~1f ~1f)" ~w/>',
           [CX, CY, RX, RY, A, CX, CY, Style]).
svg_element(smooth(Poly), Style, SVG) :-
    catmull(Poly, Data),
    format(string(SVG), '<path d="~w" ~w/>', [Data, Style]).

		 /*******************************
		 *           FIGURE		*
		 *******************************/

%!  kangaroo_shapes(+T, -Near, -Far, -Details, -Low, -ToeX) is det.
%
%   The shapes of the kangaroo at moment T, with the hip at (0,0).
%   Near and Far are the shapes of the near side and the far limbs.
%   Details is a list of Kind-Shape.  Low is the y of the lowest point
%   of the feet and ToeX the x of the toe, both scaled.

kangaroo_shapes(T, Near, Far, Details, Low, ToeX) :-
    pose(T, [_HipH, Pitch, AThigh, AShin, AFoot, ATail, AArm]),
    Hip = 0.0-0.0,
    BodyDir is -Pitch,                  % SVG: negative is up
    pt(Hip, BodyDir, 46, Shoulder),
    NeckDir is BodyDir-35,
    pt(Shoulder, NeckDir, 16, Neck),
    HeadDir is -10-Pitch*0.3,
    pt(Neck, HeadDir, 12, Head),
    % leg
    pt(Hip, AThigh, 26, Knee),
    pt(Knee, AShin, 30, Ankle),
    pt(Ankle, AFoot, 34, Toe),
    % tail
    TailDir is BodyDir+180,
    pt(Hip, TailDir, 10, TailBase),
    A1 is ATail-10, pt(TailBase, A1, 30, T1),
    A2 is ATail+5,  pt(T1, A2, 30, T2),
    A3 is ATail+18, pt(T2, A3, 24, T3),
    % arm from the chest
    ChestDir is BodyDir-8,
    pt(Hip, ChestDir, 36, Chest),
    pt(Chest, AArm, 12, Elbow),
    PawDir is AArm-60,
    pt(Elbow, PawDir, 10, Paw),
    % far limbs, slightly offset
    shift(Knee, -4, -2, FK), shift(Ankle, -4, -2, FA), shift(Toe, -4, -2, FT),
    capsule([FK, FA, FT], [6, 4, 3], FarLeg),
    pt(Chest, -60, 3, FC), pt(Elbow, -60, 3, FE), pt(Paw, -60, 3, FP),
    capsule([FC, FE, FP], [3.2, 2.6, 2.2], FarArm),
    Far = [FarLeg, FarArm],
    % tail and torso
    capsule([TailBase, T1, T2, T3], [12, 8, 5, 2], Tail),
    pt(Hip, BodyDir, 20, Mid),
    ellipse(Hip, 20, 18, BodyDir, Rump),
    ellipse(Mid, 32, 20, BodyDir, Torso),
    ellipse(Chest, 16, 14, BodyDir, ChestE),
    capsule([Shoulder, Neck, Head], [10, 7, 6], NeckS),
    % head with snout
    SnoutDir is -Pitch*0.3+12,
    pt(Head, SnoutDir, 15, Snout),
    pt(Head, 180, 4, Back),
    capsule([Back, Head, Snout], [9, 9, 4.5], HeadS),
    % ears
    pt(Head, -100, 6, EarBase),
    findall(Ear,
            ( member(K-DA, [0-0, 1-(-14)]),
              BL is 4*K,
              pt(EarBase, 180, BL, EB),
              EA is -110+DA,
              pt(EB, EA, 9, EM),
              pt(EB, EA, 17, Tip),
              capsule([EB, EM, Tip], [4.5, 4, 1.2], Ear)
            ), Ears),
    % thigh and leg
    pt(Hip, AThigh, 9, ThighC),
    ellipse(ThighC, 17, 13, AThigh, Thigh),
    capsule([Knee, Ankle, Toe], [7, 4.5, 3], Leg),
    % near arm
    capsule([Chest, Elbow, Paw], [3.5, 3, 2.5], Arm),
    append([[Tail, Rump, Torso, ChestE, NeckS, HeadS], Ears,
            [Thigh, Leg, Arm]], Near),
    % details: belly, inner ear, eye, nose
    BellyDir is BodyDir-18,
    pt(Hip, BellyDir, 26, BellyC),
    BellyA is BodyDir+10,
    ellipse(BellyC, 22, 11, BellyA, Belly),
    pt(EarBase, -110, 3, IE1), pt(EarBase, -110, 9, IE2),
    pt(EarBase, -110, 14, IE3),
    capsule([IE1, IE2, IE3], [2.2, 2, 0.6], InnerEar),
    EyeDir is -Pitch*0.3-25,
    pt(Head, EyeDir, 4, EyeC),
    ellipse(EyeC, 2.0, 2.4, 0, Eye),
    pt(Snout, 180, 1, NoseC),
    ellipse(NoseC, 2.2, 1.8, 0, Nose),
    Details = [belly-Belly, ear-InnerEar, eye-Eye, nose-Nose],
    % the feet
    figure_scale(S),
    Ankle = _-Y1, Toe = ToeX0-Y2, FT = _-Y3, FA = _-Y4,
    max_list([Y1, Y2, Y3, Y4], LowY),
    Low is LowY*S,
    ToeX is ToeX0*S.

shift(X0-Y0, DX, DY, X-Y) :-
    X is X0+DX,
    Y is Y0+DY.

ellipse(X-Y, RX, RY, A, ellipse(X, Y, RX, RY, A)).

%!  contact_x(-X) is det.
%
%   X of the toe at take-off, relative to the hip.

contact_x(X) :-
    contact(C),
    kangaroo_shapes(C, _, _, _, _, X).

		 /*******************************
		 *            FRAMES		*
		 *******************************/

%!  frame(+I, +Palette, +BaseX, -BBox, -SVG) is det.
%
%   SVG is frame I (0-based) in Palette.  BBox is bbox(X0,Y0,X1,Y1) of
%   the body parts, used to centre the hop.

frame(I, Palette, BaseX, BBox, SVG) :-
    palette(Palette, Body, Shade, Belly, Outline, EarC),
    frames(N),
    T is I/N,
    kangaroo_shapes(T, Near, Far, Details, Low, ToeX),
    frame_offset(I, T, Low, ToeX, BaseX, DX, DY),
    figure_scale(S),
    maplist(transform(S, DX, DY), Near, NearT),
    maplist(transform(S, DX, DY), Far, FarT),
    append(FarT, NearT, All),
    bbox(All, BBox),
    stroke_width(SW),
    SW2 is 2*SW,
    canvas(W, H),
    format(string(Head),
           '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ~d ~d" \c
            width="~d" height="~d">',
           [W, H, W, H]),
    maplist(svg_shape_(Shade, stroke(Outline, SW)), FarT, FarE),
    maplist(svg_shape_(Outline, stroke(Outline, SW2)), NearT, OutlineE),
    maplist(svg_shape_(Body, none), NearT, FillE),
    Colours = _{belly:Belly, ear:EarC, eye:Outline, nose:Outline},
    maplist(detail(S, DX, DY, Colours), Details, DetailE),
    append([[Head], FarE, OutlineE, FillE, DetailE, ["</svg>"]], Lines),
    atomic_list_concat(Lines, '\n', SVG0),
    atom_concat(SVG0, '\n', SVG).

svg_shape_(Fill, Stroke, Shape, SVG) :-
    svg_shape(Shape, Fill, Stroke, SVG).

detail(S, DX, DY, Colours, Kind-Shape, SVG) :-
    transform(S, DX, DY, Shape, ShapeT),
    get_dict(Kind, Colours, Colour),
    svg_shape(ShapeT, Colour, none, SVG).

%!  frame_offset(+I, +T, +Low, +ToeX, +BaseX, -DX, -DY) is det.
%
%   Position of the hip in frame I.  Vertically, the feet are on the
%   ground in contact, while in flight the hip moves from its take-off
%   to its landing height along an arc.  Horizontally the toe stays put
%   in contact and we advance a full hop over the flight time.  The
%   demo moves the figure by I steps, which we compensate.

frame_offset(I, T, Low, ToeX, BaseX, DX, DY) :-
    contact(C),
    ground_y(G),
    hop(Hop, UnitStep),
    contact_x(CX),
    (   T =< C
    ->  DY is G - Low,
        World is -ToeX
    ;   F is (T-C)/(1-C),
        kangaroo_shapes(C, _, _, _, LowT, _),
        kangaroo_shapes(0.0, _, _, _, LowL, _),
        jump(J),
        DY is (G-LowT) + ((G-LowL)-(G-LowT))*F - J*sin(pi*F),
        World is -CX + Hop*F
    ),
    DX is BaseX + World - I*UnitStep + CX.

%!  hop(-Hop, -UnitStep) is det.
%
%   UnitStep is the step of the demo in viewBox units and Hop the
%   distance covered by a hop.

hop(Hop, UnitStep) :-
    canvas(W, _),
    pixels(PX),
    step(Step),
    frames(N),
    UnitStep is Step / (PX/W),
    Hop is UnitStep*N.

transform(S, DX, DY, ellipse(CX, CY, RX, RY, A),
          ellipse(TX, TY, TRX, TRY, A)) :-
    !,
    TX is CX*S+DX, TY is CY*S+DY,
    TRX is RX*S, TRY is RY*S.
transform(S, DX, DY, smooth(Poly), smooth(TPoly)) :-
    maplist(transform_point(S, DX, DY), Poly, TPoly).

transform_point(S, DX, DY, X-Y, TX-TY) :-
    TX is X*S+DX,
    TY is Y*S+DY.

bbox(Shapes, bbox(X0, Y0, X1, Y1)) :-
    foldl(shape_points, Shapes, [], Points),
    pairs_keys_values(Points, Xs, Ys),
    min_list(Xs, X0), max_list(Xs, X1),
    min_list(Ys, Y0), max_list(Ys, Y1).

shape_points(ellipse(CX, CY, RX, RY, _), Ps0, Ps) :-
    !,
    R is max(RX, RY),
    X0 is CX-R, Y0 is CY-R, X1 is CX+R, Y1 is CY+R,
    Ps = [X0-Y0, X1-Y1|Ps0].
shape_points(smooth(Poly), Ps0, Ps) :-
    append(Poly, Ps0, Ps).

%!  layout(-BaseX) is det.
%
%   Centre the hop horizontally in the canvas.

layout(BaseX) :-
    hop_bbox(0, bbox(X0, _, X1, _)),
    canvas(W, _H),
    BaseX is (W - (X1-X0))/2 - X0.

hop_bbox(BaseX, bbox(X0, Y0, X1, Y1)) :-
    frames(N),
    Last is N-1,
    findall(BB, ( between(0, Last, I),
                  frame(I, red, BaseX, BB, _)
                ), BBs),
    maplist(arg(1), BBs, X0s), min_list(X0s, X0),
    maplist(arg(2), BBs, Y0s), min_list(Y0s, Y0),
    maplist(arg(3), BBs, X1s), max_list(X1s, X1),
    maplist(arg(4), BBs, Y1s), max_list(Y1s, Y1).
