%   Auto-generated by tmp/extract_example_summaries.pl from
%   man/refmanual/md/{examples,changes}.md on 2026-06-09T12:58:25.
%   Do not edit by hand.

:- module(example_summaries,
          [ example_summary/3   % ?Kind, ?Title, ?Summary
          ]).

example_summary(examples, "Confirm", "Enter name while application waits").
example_summary(examples, "Counting", "Counting long strings in a chain").
example_summary(examples, "Creating objects", "Basic examples on how to create objects").
example_summary(examples, "Finding objects", "Finding objects in a collection").
example_summary(examples, "Graphical relation", "Using spatials").
example_summary(examples, "Hierarchy", "Generate a tree from facts").
example_summary(examples, "Linking Graphicals", "Linking two boxes with a connection").
example_summary(examples, "Menu Bar", "Using a menu_bar in a frame").
example_summary(examples, "Menu of fill patterns", "Marked menu to select a fill").
example_summary(examples, "Multiple fonts", "Using multiple fonts in an editor").
example_summary(examples, "Obtainers", "Primitive usage of obtainers").
example_summary(examples, "Selection", "Select Graphicals").
example_summary(examples, "Text inside box", "Creating a compound graphical").
example_summary(examples, "Using Conditions", "Tests inside a dialog window").
example_summary(examples, "Window layout", "Defining a window layout").
example_summary(changes, "menu->condition", "Changed binding of @receiver").
example_summary(changes, "text_item ->typed", "Only accepts event_id").
