%   Auto-generated by tmp/extract_groups.pl from
%   reference.legacy/groups.doc on 2026-06-08T09:12:59. Do not edit by hand.

:- module(group_summaries,
          [ group_summary/2
          ]).

group_summary('3d', '3-D effect related methods').
group_summary(abort, 'Cleanup after aborting execution').
group_summary(accelerator, 'Binding the keyboard').
group_summary(action, 'Associated action').
group_summary(active, 'Activation (greying) of dialog objects').
group_summary(add, 'Adding elements to a list').
group_summary(address, 'Address specifications').
group_summary(animate, 'Behavariour to support animation').
group_summary(annotate, 'Annotating text').
group_summary(appearance, '``Look-and-feel\'\' related aspects').
group_summary(apply, 'Applying dialog windows').
group_summary(area, 'Handling size and position').
group_summary(argument, 'Argument processing').
group_summary(attributes, 'Object- and sheet attributes').
group_summary(authority, 'Access rights').
group_summary(behaviour, 'Definition of behaviour').
group_summary(binding, 'Binding the keyboard').
group_summary(build, 'Creating a parse-tree').
group_summary(cache, 'Caching information (speed up)').
group_summary(calculate, 'Compute properties').
group_summary(callback, 'Calling the host-language').
group_summary(cancel, 'Cancel event handling').
group_summary(cardinality, 'Number of elements, characters, ...').
group_summary(caret, 'Moving the insertion point').
group_summary(case, 'Case (UPPER/lower) translation').
group_summary(cell, 'Direct operations on chain cells').
group_summary(center, 'Operation on the center of areas').
group_summary(change, 'Trapping object modifications').
group_summary(check, 'Type definition and checking').
group_summary(class, 'The classes themselves').
group_summary(classify, 'Classify events').
group_summary(client, 'Controlled object').
group_summary(colour, 'Defining and managing colours').
group_summary(command, 'Process\' command specification').
group_summary(compare, 'Comparing objects').
group_summary(compatibility, 'Methods for backward compatibility').
group_summary(compilation, 'Compiling representations').
group_summary(complete, 'Automatic completion of textual constants').
group_summary(completion, 'Automatic completion of textual constants').
group_summary(components, 'Parts I\'m built from').
group_summary(condition, 'Specifying conditions').
group_summary(connect, 'Establish socket connection (IPC)').
group_summary(connection, 'Line connection graphicals').
group_summary(console, 'Controlling the host-window').
group_summary(constraint, 'Maintaining constraints and relations').
group_summary(content, 'String content').
group_summary(contents, 'Modify/query contents of object').
group_summary(context, 'Context I belong too, I am executed in').
group_summary(control, 'Control autonomous processes').
group_summary(conversion, 'Conversion (for type checking)').
group_summary(copy, 'Copying instances').
group_summary(corner, 'Specifying the corner of a graphical').
group_summary(create, 'Realising constraints').
group_summary(current, 'Operations on `current\' object').
group_summary(cursor, 'Image of the pointer (mouse) cursor').
group_summary(date_component, 'Manipulate/query components of a date').
group_summary(debugging, 'Debugging PCE programs').
group_summary(default, 'Resource default values').
group_summary(delegate, 'Delegation of behaviour').
group_summary(delete, 'Text deletion commands').
group_summary(dimension, 'Dimensions of (graphical) objects').
group_summary(display, 'X-Screen oriented behaviour').
group_summary(edit, 'Modify object').
group_summary(edit_continue, 'Temporary re-binding keys').
group_summary(element, 'Vector elements').
group_summary(encoding, 'Character-set related behaviour').
group_summary(environment, 'Handling the process\' environment').
group_summary(equality, 'Comparing objects').
group_summary(event, 'Event processing').
group_summary(exception, 'Trapping and generation exceptions').
group_summary(execute, 'Execution of dialog objects').
group_summary(feedback, 'Feedback for event-handling').
group_summary(file, 'Saving and loading files, file operations').
group_summary(file_type, 'File properties').
group_summary(fill, 'Breaking (long) text into lines').
group_summary(filter, 'Filtering file I/O').
group_summary(focus, 'Focussing events to objects').
group_summary(font, 'Available fonts').
group_summary(format, 'Formatted write (as C printf())').
group_summary(forward, 'Execute code, forwarding context parameters').
group_summary(fragment, 'Text fragments').
group_summary(function, 'Object management for functions').
group_summary(grey, 'Colour --> monochrome translation').
group_summary(group, 'Functional grouping of behaviour').
group_summary(handle, 'Connection end-point').
group_summary(hashing, 'Caching information (speed up)').
group_summary(hierarchy, 'Hierarchical structure').
group_summary(host, 'Communication with the host language').
group_summary(icon, 'Iconising Frames').
group_summary(implementation, 'Implementation of behaviour').
group_summary(indentation, 'Create/analyse text indentation').
group_summary(index, 'Position in a sequence').
group_summary(initialise, 'Realising constraints').
group_summary(input, 'Handling (process) input').
group_summary(insert, 'Text insertion commands').
group_summary(internal, 'Private behaviour').
group_summary(interpolation, 'Interpolation points for smooth lines').
group_summary(items, 'Manipulation and query items of a browser or menu').
group_summary(iterate, 'Run code on each element of a collection').
group_summary(kind, 'Category of the instance').
group_summary(label, 'Visible name of objects').
group_summary(language, 'Specialisation for specific languages').
group_summary(layout, 'Spatial relations between graphical objects').
group_summary(limit, 'Query PCE limits').
group_summary(line, 'Line oriented operations').
group_summary(list, 'List operations (add, delete)').
group_summary(location, 'Locating points').
group_summary(lookup, '(Table) lookup methods').
group_summary(manual, 'Support for the online reference manual').
group_summary(mark, 'Moving the mark').
group_summary(member, 'Find objects (by name)').
group_summary(menu, 'Associating (Popup) menus').
group_summary(meta, 'Analysing behaviour and objects').
group_summary(miscellaneous, 'Remaining behaviour').
group_summary(modal, 'Event sub-loops: modal windows').
group_summary(mode, 'Modes of operation').
group_summary(modified, 'Modification of dialog and text').
group_summary(modifier, 'Test Meta-, Shift- and Control-keys').
group_summary(name, 'Naming objects').
group_summary(nodes, 'Nodes in a hierarchy (tree)').
group_summary(obtain, 'Obtaining resource-values').
group_summary(obtained, 'Obtaining resource-values').
group_summary(oms, 'Object management operations').
group_summary(open, 'Making objects visible').
group_summary(operant, 'Operant of expression').
group_summary(order, 'Sorting sequences').
group_summary(organisation, 'Organisation of (graphical) objects').
group_summary(orientation, 'Horizontal or vertical orientation').
group_summary(output, 'Handling (process) output').
group_summary(parse, 'Specialisation for specific languages').
group_summary(part, 'Managed objects').
group_summary(path, 'File/directory path').
group_summary(pattern, 'Regular expression patterns').
group_summary(permission, 'Access rights').
group_summary(pie, 'Angles, pie-slices, etc.').
group_summary(pixel, 'Pixel manipulations').
group_summary(pointer, 'Pointer related methods').
group_summary(points, 'Reference points for a smooth line (path)').
group_summary(popup, 'Associating (Popup) menus').
group_summary(position, 'Position of objects').
group_summary(postscript, 'Generating PostScript for printing').
group_summary(process, 'Process identifier').
group_summary(programming, 'Methods to write methods').
group_summary(property, 'Font properties').
group_summary(quit, 'Exiting from PCE').
group_summary(range, 'Range of a vector').
group_summary(read, 'Reading text from objects').
group_summary(read_ahead, 'Reading data and tokens ahead (parser)').
group_summary(realise, 'Realising class definitions').
group_summary(receiver, 'Receiver of message or event').
group_summary(reference, 'Object reference manipulation').
group_summary(refine, 'Customizing objects for a specific goal').
group_summary(registers, 'Regular expression registers').
group_summary(relation, 'Relations, constraints, (graphical) connections').
group_summary(repaint, 'Behaviour dealing with repaint').
group_summary(replace, 'Text replacement commands').
group_summary(report, 'Reporting events, status and errors').
group_summary(reset, 'Aborting execution').
group_summary(resize, 'Controlling and trapping resizes').
group_summary(resource, 'Interface to ~/.Xdefault').
group_summary(root, 'Manipulation of the root window (background)').
group_summary(rotate, 'Rotating objects').
group_summary(runtime, 'Runtime version detection').
group_summary(scope, 'Scope of variable assignments').
group_summary(scroll, 'Controlling the `viewport\'').
group_summary(search, 'Finding plain text, regex or objects').
group_summary(selection, 'Manipulation and query of selections').
group_summary(server, 'Unix socket organisation (server)').
group_summary(set, 'Set operations (no duplicates)').
group_summary(side, 'Edges of graphicals').
group_summary(sort, 'Sorting sequences').
group_summary(stacking, 'Overlapping frames and graphicals').
group_summary(statement, 'Argument code object').
group_summary(statistics, 'Timing, memory usage, etc.').
group_summary(status, 'Flags indicating current status').
group_summary(storage, 'Definition of storage details').
group_summary(syntax, 'Defining a syntax (editor, parser)').
group_summary(table, 'Tabular layout of graphical objects').
group_summary(template, 'Class Template support').
group_summary(term, 'Conversion to (Prolog) term').
group_summary(test, 'Test object properties').
group_summary(textual, 'Textual representation').
group_summary(time, 'Controlling real-time').
group_summary(timing, 'Controlling real-time').
group_summary(tip, 'End-points of a joint (line, arc, path) or arrow').
group_summary(transient, 'Support windows (e.g. prompters)').
group_summary(transpose, 'Transposition of text').
group_summary(tty, 'Controlling the terminal').
group_summary(type, 'Type definition, test and conversion').
group_summary(undo, 'Undoing (edit) operations').
group_summary(update, 'Update Dependant properties').
group_summary(value, 'Related value').
group_summary(version, 'Versions of XPCE, OS, X, ...').
group_summary(virtual, 'Dummy methods on super-classes').
group_summary(visibility, 'Making object (in-)visible').
group_summary(visual, 'Behaviour related to the visual hierarchy').
group_summary(visualisation, 'Making data visible').
group_summary(whole, 'Managing object').
group_summary(window_manager, 'Interaction with the X-window manager').
group_summary(window_system, 'Connection to the underlying window system').
group_summary(working_directory, 'Process\' or PCE working directory').
group_summary(write, 'Writing to files').
group_summary(x, 'X-window interaction').
