/*  Part of XPCE --- The SWI-Prolog GUI toolkit

    Author:        Jan Wielemaker
    E-mail:        jan@swi-prolog.org
    WWW:           http://www.swi-prolog.org
    Copyright (c)  2026, SWI-Prolog Solutions b.v.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in
       the documentation and/or other materials provided with the
       distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/

:- module(gen_refman,
          [ gen_refman/2,                       % +InDir, +OutDir
            gen_refman_check/1                  % +InDir
          ]).

%   The xpce library directory (sibling of this file) supplies
%   pldoc_xpce. Make it visible before any use_module so the script is
%   self-contained when invoked from CMake.

:- prolog_load_context(directory, ThisDir),
   atomic_list_concat([ThisDir, '/../../prolog/lib'], XpceLib),
   asserta(user:file_search_path(library, XpceLib)).

:- use_module(library(main)).
:- use_module(library(pldoc/doc_wiki), [wiki_codes_to_dom/3]).
:- use_module(library(doc_latex)).
:- use_module(library(pce), []).
:- use_module(library(pldoc_xpce),
              [ with_xpce_backend/2,
                with_xpce_chapter_class/2,
                xpce_dom_transform/2
              ]).
:- use_module(library(filesex), [make_directory_path/1, directory_file_path/3]).
:- use_module(library(lists)).
:- use_module(library(option)).
:- use_module(library(apply)).
:- use_module(library(readutil), [read_file_to_codes/3]).

:- initialization(main, main).

/** <module> Build the xpce reference manual from per-class .md files

This script translates each =|*.md|= file under InDir into a matching
=|.tex|= file under OutDir, and emits an aggregate include file
=|chapters.tex|= that the top-level driver (=|xpcerefman.plx|=) reads
to assemble the manual.

Class chapters get a per-class prefix on their output filename
(=|class-<name>.tex|=); the nine top-level reference modules
(=bug_fixes=, =changes=, ..., =topics=) keep their bare name.

The script is invoked from the build with:

    swipl -f none -g 'gen_refman:main' -- <in-dir> <out-dir>
*/

main(Argv) :-
    (   Argv = ['--check', InDir]
    ->  gen_refman_check(InDir)
    ;   Argv = [InDir, OutDir]
    ->  gen_refman(InDir, OutDir)
    ;   format(user_error,
               'Usage: swipl gen_refman.pl -- [--check] <in> [<out>]~n',
               []),
        halt(1)
    ).


                 /*******************************
                 *           BUILDER            *
                 *******************************/

%!  gen_refman(+InDir, +OutDir) is det.
%
%   Render every =|*.md|= under InDir to =|<out>/<name>.tex|=, and
%   emit =|<out>/chapters.tex|= with one =|\input|= per chapter,
%   ordered classes-first then top-level modules.

gen_refman(InDir, OutDir) :-
    make_directory_path(OutDir),
    md_files(InDir, Files),
    partition_chapters(Files, Classes, Modules),
    msort(Classes, ClassesSorted),
    forall(member(F, Files),
           ignore(render_chapter(InDir, OutDir, F))),
    open_done(OutDir, 'chapters.tex',
              [ '% Auto-generated by gen_refman.pl -- do not edit by hand.\n',
                '\\chapter{Classes}\n',
                '\\label{sec:classes}\n'
              ]),
    forall(member(F, ClassesSorted),
           append_input(OutDir, 'chapters.tex', class, F)),
    forall(member(Mod, [topics, objects, predicates, examples, errors,
                        tools, groups, bug_fixes, changes]),
           ( memberchk(Mod-_, Modules)
           ->  append_module_chapter(OutDir, Mod)
           ;   external_module_chapter(Mod)
           ->  append_module_chapter(OutDir, Mod)
           ;   true
           )).

%   Modules whose .tex is produced outside the .md pipeline. predicates
%   is generated by doc2tex from predicates.plx, so it has no .md to
%   walk but still needs its chapter wrapping.

external_module_chapter(predicates).

%!  gen_refman_check(+InDir) is det.
%
%   Parse every =|*.md|= under InDir through the wiki/markdown parser
%   without emitting output; intended as a CI regression guard. Errors
%   exit non-zero.

gen_refman_check(InDir) :-
    md_files(InDir, Files),
    length(Files, N),
    format("~w .md files to check in ~w~n", [N, InDir]),
    foldl(check_one(InDir), Files, 0, Failures),
    (   Failures =:= 0
    ->  format("All files parse cleanly~n")
    ;   format(user_error,
               '~w file(s) failed to parse~n', [Failures]),
        halt(1)
    ).

check_one(InDir, FileName, F0, F) :-
    directory_file_path(InDir, FileName, Path),
    (   catch(parse_md(Path), E, (parse_err(FileName, E), fail))
    ->  F = F0
    ;   F is F0 + 1
    ).

parse_md(Path) :-
    read_file_to_codes(Path, Codes, []),
    wiki_codes_to_dom(Codes, [], _DOM).

parse_err(File, Err) :-
    format(user_error, '~w: ~p~n', [File, Err]).


                 /*******************************
                 *         FILE WALK            *
                 *******************************/

md_files(Dir, Files) :-
    directory_files(Dir, Entries),
    include(is_md, Entries, Files).

is_md(Name) :-
    file_name_extension(_, md, Name).

%   The xpce manual has nine top-level reference modules whose names
%   are reserved; every other =|*.md|= is treated as a class chapter.

top_module(bug_fixes).
top_module(changes).
top_module(errors).
top_module(examples).
top_module(groups).
top_module(objects).
top_module(predicates).
top_module(tools).
top_module(topics).

partition_chapters([], [], []).
partition_chapters([F|T], Classes, [Mod-F|Modules]) :-
    file_name_extension(Base, md, F),
    atom_string(BaseA, Base),
    top_module(BaseA),
    !,
    Mod = BaseA,
    partition_chapters(T, Classes, Modules).
partition_chapters([F|T], [F|Classes], Modules) :-
    partition_chapters(T, Classes, Modules).


                 /*******************************
                 *           RENDER             *
                 *******************************/

render_chapter(InDir, OutDir, MdFile) :-
    directory_file_path(InDir, MdFile, InPath),
    out_basename(MdFile, OutBase),
    file_name_extension(OutBase, tex, OutFile),
    directory_file_path(OutDir, OutFile, OutPath),
    render_md_to_tex(InPath, OutPath).

out_basename(MdFile, OutBase) :-
    file_name_extension(Base, md, MdFile),
    atom_string(BaseA, Base),
    (   top_module(BaseA)
    ->  OutBase = BaseA
    ;   atom_concat('class-', BaseA, OutBase)
    ).

%   The enclosing class for an InPath is just its bare base name --
%   class files are written as =|<class>.md|=, top-level modules as
%   their bare module name. Top-level chapters get an empty class
%   so local-form refs stay as =|\send{...}|=.

chapter_class(InPath, Class) :-
    file_base_name(InPath, Base),
    file_name_extension(Stem, md, Base),
    atom_string(StemA, Stem),
    (   top_module(StemA)
    ->  Class = ''
    ;   Class = StemA
    ).

%   Render the .md through wiki_codes_to_dom + doc_latex with the
%   xpce LaTeX backend selector active, so the inline xpce face terms
%   become the matching xpce.sty macro calls.

render_md_to_tex(InPath, OutPath) :-
    chapter_class(InPath, Class),
    catch(
        ( read_file_to_codes(InPath, Codes, []),
          wiki_codes_to_dom(Codes, [], DOM0),
          xpce_dom_transform(DOM0, DOM),
          with_xpce_backend(latex,
              with_xpce_chapter_class(Class,
                  phrase(pldoc_latex:latex(DOM), Tokens, []))),
          setup_call_cleanup(
              open(OutPath, write, Out),
              pldoc_latex:print_latex(Out, Tokens, [stand_alone(false)]),
              close(Out))
        ),
        E,
        ( format(user_error,
                 "% chapter render failed for ~w: ~p~n",
                 [InPath, E]),
          fail )).


                 /*******************************
                 *         CHAPTERS.tex         *
                 *******************************/

open_done(OutDir, BaseName, Header) :-
    directory_file_path(OutDir, BaseName, Path),
    setup_call_cleanup(
        open(Path, write, Out),
        ( forall(member(L, Header), write(Out, L)) ),
        close(Out)).

append_input(OutDir, BaseName, Kind, MdFile) :-
    directory_file_path(OutDir, BaseName, Path),
    out_basename(MdFile, OutBase),
    setup_call_cleanup(
        open(Path, append, Out),
        format(Out, '\\input{~w}  % ~w~n', [OutBase, Kind]),
        close(Out)).

append_module_chapter(OutDir, Mod) :-
    directory_file_path(OutDir, 'chapters.tex', Path),
    module_chapter_title(Mod, Title),
    safe_label(Mod, Label),
    setup_call_cleanup(
        open(Path, append, Out),
        ( format(Out, '~n\\chapter{~w}~n', [Title]),
          format(Out, '\\label{sec:~w}~n', [Label]),
          format(Out, '\\input{~w}~n', [Mod])
        ),
        close(Out)).

%   PlDoc's section_label/1 strips underscores via
%   delete_unsafe_label_chars/2; do the same here so \label{sec:bug_fixes}
%   doesn't get LaTeX-mangled at .aux re-read time.

safe_label(In, Out) :-
    atom_chars(In, Chars),
    delete(Chars, '_', Safe),
    atom_chars(Out, Safe).

module_chapter_title(bug_fixes,  'Bug fixes').
module_chapter_title(changes,    'Changes').
module_chapter_title(errors,     'Errors').
module_chapter_title(examples,   'Examples').
module_chapter_title(groups,     'Method groups').
module_chapter_title(objects,    'Global objects').
module_chapter_title(predicates, 'Predicates').
module_chapter_title(tools,      'Tools').
module_chapter_title(topics,     'Topics').
