#!/bin/sh
# Generate Emacs tag table.  Either invoke as one of
#
#	./mktags x11
#	./mktags msw
#	./mktags ray
#	./mktags sdl
#
# To create a tag-table for the proper environment.   Default is `x11`

if [ ! -z "$1" ]; then win="$1"; else win=x11; fi

modules="adt ari evt gnu gra img itf ker men msg prg rel rgx txt unx win fmt box"

files=""

for d in h $modules $win; do
  files="$files `echo $d/*.[ch]`"
done

etags $files
