#!/bin/sh
# Generate Emacs tag table.  Either invoke as one of
#
#	./mktags
#
# To create a tag-table for the proper environment.   Default is `x11`

modules="adt ari evt gnu gra img itf ker men msg prg rel rgx txt unx win fmt box"

files=""

for d in h $modules sdl msw; do
  files="$files `echo $d/*.[ch]`"
done

etags $files
