#!/bin/sh

arch=$1

echo "[ERROR: No machine description file for PLARCH=$arch]"

arches=`ls md | grep -v CVS | sed 's/md-\(.*\)\.h/\1/'`

echo ""
echo "Please edit PLARCH in Makefile to be one of:"
for a in $arches; do echo "	$a"; done
exit 1
